### PR TITLE
Added room rotation and template door disabling

### PR DESCRIPTION
**Pull request by SkySourced**

### CODE REVIEW

**Comment by SkySourced** [comment]
i forgot half of the content for this pull request

**Review by Thechiefpotatopeeler — APPROVED** [review]
"Plink plonko" indeed

**Comment by SkySourced** [comment]
what have you done

**Comment by Thechiefpotatopeeler** [comment]
Gabe was getting pissed at me for not attacking in clan war right when I was reviewing.

**Comment by themoonboyx** [comment]
lol

**Pull request merged**
